language: php
php:
    - "5.6"
before_install:
    - composer self-update
before_script:
    - composer install
script: phpunit --configuration module/Skel/tests/phpunit.xml --coverage-text
# notifications:
#     webhooks: http://code-squad.com/travis/notification